version: '3'
services:
  postgres:
    container_name: managym-postgress
    image: postgres
    restart: always
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  app:
    container_name: managym-app
    build: ./app/
    restart: always
    ports:
      - "4567:4567"
    depends_on:
      - postgres